### ISSUE TITLE
Roadmap to version 1.0.0

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/canvas-sketch#116]
Although canvas-sketch is relatively stable, there's a lot of things I'd like to improve before publishing a "stable" 1.0 release. I probably won't have bandwidth to work on these changes until mid-2021, but happy to have discussions and look at PRs.

## Changes

- [ ] Better MP4/ffmpeg handling, should be built-in and enabled by default: https://github.com/mattdesl/canvas-sketch/issues/115 https://github.com/mattdesl/canvas-sketch/issues/59
- [ ] Bundler: https://github.com/mattdesl/canvas-sketch/issues/112 https://github.com/mattdesl/canvas-sketch/issues/109 https://github.com/mattdesl/canvas-sketch/issues/63
- [ ] UI + Controls + Hotkeys: https://github.com/mattdesl/canvas-sketch/issues/104 https://github.com/mattdesl/canvas-sketch/issues/38 https://github.com/mattdesl/canvas-sketch/issues/20 https://github.com/mattdesl/canvas-sketch/issues/8
- [ ] Better Support/Docs for Manual Rendering: https://github.com/mattdesl/canvas-sketch/issues/101
- [ ] Interactive Shader Format: https://github.com/mattdesl/canvas-sketch/issues/93
- [ ] Fix git commit issues: https://github.com/mattdesl/canvas-sketch/issues/92
- [ ] Global and per-project settings: https://github.com/mattdesl/canvas-sketch/issues/82
- [ ] Better SVG export tools: https://github.com/mattdesl/canvas-sketch/issues/76 https://github.com/mattdesl/canvas-sketch/issues/47
- [ ] Basic website/frontend with interactive code examples: https://github.com/mattdesl/canvas-sketch/issues/62 https://github.com/mattdesl/canvas-sketch/issues/36
- [ ] Rethink 'settings' to support things like multiple output formats (MP4+GIF together for example) https://github.com/mattdesl/canvas-sketch/issues/18
- [ ] Possibly explore auto module installation & resolution https://github.com/mattdesl/canvas-sketch/issues/17
- [ ] Consider declarative rendering as an option, perhaps for v2.0 – [mattdesl/yyz](https://github.com/mattdesl/yyz)

**Comment by robertoranon** [comment]
Hi, 
   love canvas-sketch so far. Two things I'd like, perhaps they are already available, but haven't figured out how to use them:
- I'd like to export a movie programmatically, i.e., from my sketch, turn recording on/off
- suppose I have a sketch with some parameter, I'd like to draw a grid with mxn instances of my sketch, where each one takes a different value for the parameter
Thanks for your work!

**Comment by el-schneider** [comment]
Nice! Definitely looking forward to it. Especially implementation of a new bundler.

**Comment by Jeremboo** [comment]
Hi @mattdesl!  I'm still using canvas-sketch to prototype and play around ideas since years. But I get often annoyed with some old issues never fixed like the bundler.

So I wonder if you still plan to work on this repo or looking for help.
Maybe you do not recommend to use it anymore ?

Thanks

**Comment by mattdesl** [comment]
Hey @Jeremboo—maintenance on canvas-sketch has stalled a bit. The next version will have to be a complete rewrite (swapping out browserify is a large task) and I’d like to use some of the PNG, MP4, GIF and other media encoding tools I’ve been developing lately, which aren’t all complete yet.

For now, it might be better to use Vite or Fragment until I get around to rolling a new version of canvas-sketch. Since it will be so different, I might end up making a new package and deprecate canvas-sketch.

https://github.com/raphaelameaume/fragment

**Comment by Jeremboo** [comment]
Thanks @mattdesl ! Let us know if you would like to delegate some minor tasks at a certain point, I'll be happy to help 🙂 

As always thanks for sharing your tools with the community! Waiting for the next version once you'll have time to work on it!

**Comment by sfrieson** [comment]
Also glad to help with any tasks!

**Comment by howardah** [comment]
Also happy to contribute!
